backend:
  name: github
  repo: rickthedev/ivo

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Card"
    name: "card"
    folder: "/src/cards"
    create: true
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["Schilderij", "Grafisch", "Goudsmit"],
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - {
          label: "Availability",
          name: "availability",
          widget: "select",
          options: ["Available", "Reserved", "Sold"],
        }
      - { label: 'Description', name: 'description', widget: 'markdown' }
