collections:
  - label: "Card"
    name: "card"
    folder: "/src/cards"
    create: true
    fields:
      - {label: "Availability", name: "availability", widget: "select", options: ["available", "reserved", "sold"]}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      